# Generated by Django 5.1.7 on 2025-05-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly budget goal for this category (for expense categories)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='budget.category'),
        ),
    ]
